### ISSUE TITLE
Game crashes after repacking files.

### ISSUE THREAD

**Issue by femtofox** [marcussacana/MwareStuff#1]
Hello,
Thank you for your effort in making this tool, I appreciate it very much.

I came  across this problem, when I tried unpacking and repacking the script.npk without making changes to it and placing the new repacked script.npk file in the game folder the game crashed, showing me an error.

I wasn't sure if I had to repack the folder containing the `media` folder, or just the `media` folder, so i tried both alternatives, and both crashed my game.

![image](https://user-images.githubusercontent.com/41311600/81623319-cd8c2200-93b8-11ea-8f4f-14425d2219c5.png)

**Comment by marcussacana** [comment]
that's strange, upload to me the script.npk that you repacked and your original one.
![image](https://user-images.githubusercontent.com/10576957/81624800-8197a800-93cd-11ea-8676-e136267179b4.png)
as you can see, here I translated the game without problem at least.

**Comment by femtofox** [comment]
Thanks for your prompt answer.
Yes, indeed.  It was my fault, somewhere along the process i messed up. I went and did it again and now the game runs without any issues.

I'm sorry if i would be talking off-topic, I get that the files can't be edited with any normal editor since there's a problem with character limit. And excuse my ignorance, but after compiling the nut editor I get a .dll file. How would i go about using it?

**Comment by marcussacana** [comment]
Yeah, it's just an dll, that tool is a library to be used in programs that can edit scripts.
If you want a working editor you can use the https://github.com/marcussacana/SacanaWrapper/
you will found a plugin called Nut Editor, just install it.

**Comment by femtofox** [comment]
Perfect. Thank you very much. It's working now.

**Comment by Kinariha1110** [comment]
Hello, I got the same problem : the game crashes after I repacking files. But I don't understand how you managed to solve the problem, what did you do?
