### ISSUE TITLE
edit text.

### ISSUE THREAD

**Issue by satanahorror** [marcussacana/MwareStuff#10]
Most likely not on the topic of the question, but how to correctly do it.
I translated and replaced it, but it flew out, and the text is written differently.
I know that this file belongs to a specific scene, but it is written quite diff
erently than in the game.
How does it even work?!
![image](https://user-images.githubusercontent.com/34862196/91100359-79aefb80-e67e-11ea-8c22-fe4043250a09.png)

**Comment by satanahorror** [comment]
![image](https://user-images.githubusercontent.com/34862196/91100404-95b29d00-e67e-11ea-95b6-49fc9d842e85.png)
Game

**Comment by marcussacana** [comment]
I supose you used my sacana wrapper, rigth?
when you install the NUTEditor you have 2 options, a UTF8 one and SJIS one.
I don't know what option you used, but try change to the other option then extract the script again.
Also, if the game is using SJIS and you're trying put chinese chars forget, SJIS don't support.

**Comment by satanahorror** [comment]
THANKS!!!!!
use UTF8!

**Comment by Crimsonsq** [comment]
I have The same problem but mine is Thai. I did change to UTF8 in nuteditor but still in a weird looking word. Can you help me?

**Comment by marcussacana** [comment]
You change to UTF8 only when the text is weird when extracting.
You can't change to UTF8 because your language is not supported by the SJIS.

**Comment by Crimsonsq** [comment]
Thx for reply.

I did find my mistake with SRL. I change The font To But didn't delete ; infront of To 
My Thai font work perfect now.
Maybe this is why it have weird looking word Idk I stupid at programing as long as it work for me It's "work"

**Comment by Crimsonsq** [comment]
Sorry for disturbing you again.

I want to change in game character name I find this

![Image](https://github.com/user-attachments/assets/b0fa8aef-d595-433e-b6a4-570223f7e41e)

This is a character name but in this code it in japan but in game it's eng idky
So I blindly change this to thai and get in the game.
The result is It is still his name in eng.
I don't know what to do I want to change name eng > thai Can you give me a little help?
