### ISSUE TITLE
Question about font

### ISSUE THREAD

**Issue by satanahorror** [marcussacana/MwareStuff#11]
Replaced all fonts in the font folders, but the font has not changed.
![image](https://user-images.githubusercontent.com/34862196/91215388-e1704f80-e72d-11ea-91da-44c1c7a700e0.png)
this is the font itself.
![image](https://user-images.githubusercontent.com/34862196/91215407-e6cd9a00-e72d-11ea-806d-92d0b411ebb6.png)
game Minikui Mojika no Ko

Delete Font.npk
It still works, where does it get the fonts from?

**Comment by marcussacana** [comment]
Hmmm, strange, not sure what I can reply to you here... but for now, try use the SRL, enable the CreateFontW hook, then use the srl to change the font to your one, if not works... hell yeah, that is strange.
try extract all packages of the game and ensure if don't exist more fonts.

**Comment by satanahorror** [comment]
There are no more fonts. I can send you fully disassembled files

**Comment by satanahorror** [comment]
CreateFontW hook?
this is the first I've heard of it.

---------
I unpacked system.npk, there is a setting.ini file there.
This file contains the following:
```
[Init]
SCREEN_WIDTH=1280
SCREEN_HEIGHT=720
WINDOW_NAME="‚Э‚Й‚­‚ўѓ‚ѓWѓJ‚МЋq"
#DOCKING=0#‰рЏњ
DOCKING=1#ѓhѓbѓN
#SOUND_TYPE="CRIAdx2"
SOUND_TYPE="XAudio2"
#CODE_PAGE="UTF8"
CODE_PAGE="SJIS"

[App]
VERSION="1.00"
SAVE_PATH="<APPDATA>/Nitroplus/‚Э‚Й‚­‚ўѓ‚ѓWѓJ‚МЋq/1.00"

[Font]
FOT-ѓ†ѓgѓЉѓЌ Pro M="media/font/FOT-UtrilloPro-M.otf"
FOT-ѓZѓUѓ“ѓk Pro DB="media/font/FOT-CezannePro-DB.otf"
FOT-ѓZѓUѓ“ѓk Pro M="media/font/FOT-CezannePro-M.otf"
```
I deleted it:
```
[Font]
FOT-ѓ†ѓgѓЉѓЌ Pro M="media/font/FOT-UtrilloPro-M.otf"
FOT-ѓZѓUѓ“ѓk Pro DB="media/font/FOT-CezannePro-DB.otf"
FOT-ѓZѓUѓ“ѓk Pro M="media/font/FOT-CezannePro-M.otf"`
```
and still the game worked and accepted the old fonts.
I don't know what else to do :(

**Comment by satanahorror** [comment]
StringReloads-difficult.
I am very stupid :p

**Comment by satanahorror** [comment]
do you have telegram, or facebook?
I'd like to talk it over there.
If you don't mind.
It is very difficult to write here.

**Comment by satanahorror** [comment]
sorry

**Comment by marcussacana** [comment]
Nop, I dislike to talk personally because here is a public place, maybe someone can have the same problem like you and read this to know what to do.
If you're with doubt of what do with the SRL, take a look in the Specific-Games Repostorie in my github,
Take a look in this example https://github.com/marcussacana/MwareStuff/issues/3#issuecomment-629881483
You just need change in the end of the SRL.ini the `To=` to your font face name.

**Comment by satanahorror** [comment]
I don't understand how to work with SRL.
The auto-installer does not support the engine, and it is difficult for me to install it manually

**Comment by satanahorror** [comment]
I set the font, but it didn't work.
Just stupid encoding of the old font changed or whatever.
```
[Font.0]
From=*
;FromWidth=10
;FromHeight=10
;FromCharset=0
;To=Kautiva Cyrillic Black
Charset=0
Width=00
Height=50
```
![image](https://user-images.githubusercontent.com/34862196/91305404-732a9c00-e7c4-11ea-88ca-3d112f37bbf1.png)

**Comment by satanahorror** [comment]
```
;FromWidth=10
;FromHeight=10
```
is this the location of the text?

**Comment by satanahorror** [comment]
![image](https://user-images.githubusercontent.com/34862196/91339535-0f1dcd00-e7f0-11ea-94f8-ea6fcc9e80f0.png)
WORK!
Do I need to delete the SRL after manimulations?

**Comment by satanahorror** [comment]
Since the game will be installed by others, it will need to draw fonts, they can not be transferred?

**Comment by marcussacana** [comment]
Nop, you can't delete. the SRL will be needed to change the game font.
Also, The user need install the font, but maybe you can overwrite that fonts in the font.npk and maybe, maybe the SRL will load it without install in the windows, test it to ensure.

**Comment by marcussacana** [comment]
Impossible with my tools, maybe with the nutcracker, take a look in this issue https://github.com/marcussacana/MwareStuff/issues/7
Maybe you wanna change the position because of the new font size? you can comment the Width and Height in the SRL.ini to restore the original game font size.

**Comment by satanahorror** [comment]
I don't understand how this tool works

**Comment by marcussacana** [comment]
Are you saying about the nutcracker or the SRL?

**Comment by satanahorror** [comment]
nutcracker

**Comment by marcussacana** [comment]
Srry i didn't used that one too. try ask help in the repo of that tool

**Comment by satanahorror** [comment]
Thanks for the help. I don't know what's going to happen. You can close the topic if you think that the issue has been resolved.
