### ISSUE TITLE
How to open NUT files

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/MwareStuff#12]
Hi Fisch here.
Thanks for this script I really appreciate it but I have a question.
Do you know how to open Nut files? When I tried to open npk files it shows drag and drop but now I haven't this featture for Nut.
Can you help me? Thanks.

**Comment by fisch123456** [comment]
Also drop files are gone.
Do I need some special programs to work?
Sorry for inconvenience.

**Comment by marcussacana** [comment]
https://github.com/marcussacana/MwareStuff/issues/9

**Comment by fisch123456** [comment]
Thanks it helped. Now I got this four files. Is that all or I missed something? I tried to debug it through visual studio and it gives me this. Am I doing it right? Thanks for help.

**Comment by marcussacana** [comment]
Read again

**Comment by fisch123456** [comment]
I understand but is this all files I can get? I just want to be sure. Thanks.

**Comment by marcussacana** [comment]
in this repo yes

**Comment by fisch123456** [comment]
Thank you very much.
