### ISSUE TITLE
problem with replacing text

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/MwareStuff#13]
Hi Fisch here.
After I opened all nut files I thought that i just replace the text and everything will work but unfortunetely it doesn't.
Am I missing some step because when I replaced text in ddlc it worked.
![SUCCES](https://user-images.githubusercontent.com/69847532/95115531-ede0c280-0745-11eb-961b-3fb46ff575a1.PNG)
![STAIRCASE](https://user-images.githubusercontent.com/69847532/95115568-fafdb180-0745-11eb-9fe7-fd8acd0c4cb5.PNG)
This game is from Steam.
Hope I am not opening replicate.
Thanks for answer.

**Comment by marcussacana** [comment]
Huh, I saw this problem before but I don't remember what is....
hmm, try re-extract the repacked files and see if what failed is the NUTEditor or the NPK3Tool

**Comment by fisch123456** [comment]
Hi, I think i move forward because after reinstalling and erasing ununpacked npk files i got error.
Can I ask you.
How to repack npk files with your tools?

**Comment by marcussacana** [comment]
usually just drag&drop, then just select the correct game

**Comment by fisch123456** [comment]
Hi i tried something and get this.
![subor2](https://user-images.githubusercontent.com/69847532/95263870-bf8ae200-082e-11eb-804b-3f163fb127b2.PNG)
But nothing changed.
Is that right or i did a mistake?
Do you think Steam can actualizate games so it can't  never be translated?
Thanks for answer.

**Comment by marcussacana** [comment]
first, don't left that _New in the file name, also, this don't looks a bug in my program, you're just doing something wrong probabbly.

**Comment by fisch123456** [comment]
Thanks that helped i fixed that.
I discovered that I still must repack nut files.
I know I asked you this before but I am unable to repack nut files with npk3tool.
Is there a tool to repack it?
Can you help? Thanks.

**Comment by marcussacana** [comment]
I don't really get but okay

**Comment by fisch123456** [comment]
For better explanation.
I changed suffix from txt to nut
But it gives me this error
![eror6](https://user-images.githubusercontent.com/69847532/95334169-0ff55480-08ae-11eb-8711-e61d0bb44279.PNG)
What I am asking is if i did a right step repacking nut files by changing the suffix.
And if possible advice how to fix the error problem.
Thanks

**Comment by marcussacana** [comment]
the .txt files genareted by the NUTEditor aren't readable by the game and can be used for translate the original .nut files, you must export back the translation to the NUT file and then the game can read it.

**Comment by fisch123456** [comment]
By Stringtool? Because when I tried to open it with it it gives me another dump-
![subor3](https://user-images.githubusercontent.com/69847532/95388910-56b96d80-08f3-11eb-9ab3-37ce10cc2516.PNG)
text file

**Comment by fisch123456** [comment]
Hi marcus It's me Fisch again.
I am sorry for contacting you again but I discovered a strange  bug.
When I tried to erase some text from text directory the voices disappear and bar starts to show empty text.
Do you know something about it?
I am sending you a pictures
Original
![text1](https://user-images.githubusercontent.com/69847532/95620807-049e5680-0a71-11eb-8bad-c0588b6d2f11.PNG)
modified
![subor 2](https://user-images.githubusercontent.com/69847532/95621178-90b07e00-0a71-11eb-9b1e-bb72c15dc7d8.PNG)
![bug](https://user-images.githubusercontent.com/69847532/95621309-c190b300-0a71-11eb-88b6-ac6b62c04769.PNG)
Thanks for answer

**Comment by fisch123456** [comment]
Hi sorry for interupting but I think I found a bug.
After I wanted to translate something it shows me empty bar.
It was always with this name 縲宣医・惠蠢・ｸ縲・
I think that Stringtool can't read it and shows this giberish marks.
If I am wrong I am sorry.
But is there a way how to solve this?
Thanks for answer
![subor 2](https://user-images.githubusercontent.com/69847532/95637663-97032200-0a92-11eb-9771-cc070e51c2dd.PNG)

**Comment by marcussacana** [comment]
send me the script

**Comment by fisch123456** [comment]
![text1](https://user-images.githubusercontent.com/69847532/95639030-28749300-0a97-11eb-987d-fad35f696662.PNG)- here is original
![subor 2](https://user-images.githubusercontent.com/69847532/95639049-39bd9f80-0a97-11eb-94f0-395dfa87396c.PNG)
here is modified

**Comment by marcussacana** [comment]
Wrong encoding, the Plugin Manager have 2 NUTEditor when you install the wrong things like that happen

**Comment by fisch123456** [comment]
I got installed both of them. Should I uninstall one of them?
If yes which one?
