### ISSUE TITLE
cg case

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/MwareStuff#14]
Hi Fisch here.
I would like to request for advice.
I wanted to change script in Miyuki infinite routes part Mysterious box.
I erased alergic cat text and replaced it with kill the cat but then I realised that these two text have different cg.
Do you know something about it what can help me?
if no close the issue.
Thanks.

**Comment by marcussacana** [comment]
no, my entire github, for all tools that I made, basically aims only to translate the game scripts, not edit them.

**Comment by fisch123456** [comment]
Hi Fisch again.
Maybe this is a little stereotype asking you all the time but I would like to know the answer.
I already know that your tool accept only same part of the script so programer must pay attention to that.
What I am asking you is if you have any experience with changing cgs because I got a strange problem.
When I want to change the cg for script in nut directory
 it gives me  game error.
I am asking you this because this is not problem of your tools.
But I am asking you this beacuse you are(I think) A translator of visual novels.
Do you have any experience with changing cgs in these visual novels?
Here I attach a photo and explanation what am I trying to do.
![cg error](https://user-images.githubusercontent.com/69847532/95919932-bf4e9180-0dae-11eb-93cb-8efc6a786134.png)
If you can't help just close this issue.

**Comment by marcussacana** [comment]
Usually I don't care to modify the game images, because my translations is based from english games, this mean they're already edited, the english game menu is good enough to be released with a Portuguese translation, then I really don't really care to edit the game images.
But usually replace the image is usually easy, some few cases will be a pain, when you want change the image size, maybe the image pixel format as well, or in more rare cases, some few engines reference the files in the packages by id instead name, in that rare cases you can't really replace then without lost the original one or disassembly the entire game script.

**Comment by fisch123456** [comment]
Thank you for answer 
I am sorry but probably I don't describe my problem correctly.
When I want to change cg I don't mean change cg size or something but I mean that I can't replace cg line to text file
For better describe I will use a photo.
Sorry for my bad drawing and thanks for answer.
![cg error](https://user-images.githubusercontent.com/69847532/95977280-fa85aa80-0e18-11eb-9184-83ccb9b0d959.png)

**Comment by fisch123456** [comment]
Hope I am not interupting or anything but I really need to know the answer.
If you can't help just let me know.
Thank you.

**Comment by fisch123456** [comment]
Also can I ask you if your tool can add text or sprite images or change sprite images into text?
Thanks Hope I don't bothering.

**Comment by fisch123456** [comment]
Hi.
Sorry that I am bothering again and talking little out of topic but...
I would like to ask you if you know how totono game generate questions randomly.
Is there a file for it?
I looked everywhere and found only Miyuki character question String.
Have a nice day.
Thanks for answer.
