### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/MwareStuff#15]
Hi Fisch here.
Sorry that I am interupting.
But I have a request.
I know that I was asking you so much question and I am sorry for that.
But I have maybe last one.
I really need to edit Totono file.
I CAN EVEN PAY YOU IF  IT IS NECESSSARY
Just answer me or close this issue.
Thanks.

**Comment by marcussacana** [comment]
As I said, my tools are to translate, and only translate the game texts, you can't edit the script content.

**Comment by fisch123456** [comment]
OK thanks anyway

**Comment by fisch123456** [comment]
Hi I don't want to bother you but I need a help.
Can you tell me where can I find MWare engine?
I looked everywhere but I can't find him.
