### ISSUE TITLE
I don't understand how to run the command to extract the files.

### ISSUE THREAD

**Issue by DarkMrMewtho** [marcussacana/MwareStuff#18]
I am trying to decompile the ToToNo files, and _**when I get to the step of run the command I don't know what to do.**_
What I can do?

**Comment by marcussacana** [comment]
Drag and drop

**Comment by marcussacana** [comment]
Probably is just the Steam protection stopping you...
You must crack the game before do that, also, the totono key is already
included in the npk3 tool, then you don't need use the key finder.

Em ter., 3 de nov. de 2020 às 12:26, DarkMrMewtho <notifications@github.com>
escreveu:
