### ISSUE TITLE
Question about nut file

### ISSUE THREAD

**Issue by wfsaya** [marcussacana/MwareStuff#19]
I was so lucky to find your work here, I've been writing code trying to unpack,repack and translate minikuimojikanoko. Beacause I'm new to programming, it took me a long time.I finished unpacking and repacking, but when translate the .nut file,I meet some problem I can't handle. It seems like It a script file complied to bytecode that I can't undertand

I find text may need to be translated through finding 0x10000008,then I translate the text,modify the length(4 bytes) after 0x10000008.The only thing I changed is the text and length,everything else is the same as the original nut file. But when I repack, the game will crash while reading the nut file I have modified.
Could you please teach me how I can modify the nut file correctly.Thank you verry much!!
(I major in Japanese and know little about software.if you do not understand way I talk, please forgive me)

**Comment by marcussacana** [comment]
here:
https://github.com/marcussacana/MwareStuff/blob/a9ca8cbada29fda3a7bb83352aeb69cd829a9022/NUTEditor/NUT.cs#L44-L46

**Comment by wfsaya** [comment]
> here:
> https://github.com/marcussacana/MwareStuff/blob/a9ca8cbada29fda3a7bb83352aeb69cd829a9022/NUTEditor/NUT.cs#L44-L46

Thank you soooo much! I think I can modify it now through reading your code.
But I still wonder where I can get the information about the nut file? Is it a private format of nitroplus?
(T-T)to know ablout this,do I need to learn about the game engine scripting theroy?

**Comment by marcussacana** [comment]
Yes, is private, just the usual.
