### ISSUE TITLE
New Game!

### ISSUE THREAD

**Issue by satanahorror** [marcussacana/MwareStuff#20]
A new game based on this engine will be released soon -
https://www.nitrochiral.com/game/slow-damage/
 Will it be possible to pull out the files of this game?

I looked at the trial version, files like other games on this engine
![image](https://user-images.githubusercontent.com/34862196/102159141-c2e0c080-3ea4-11eb-93a6-7bcfc5392539.png)

**Comment by marcussacana** [comment]
maybe, try use the Mwarehook tool to find the game key

**Comment by satanahorror** [comment]
I'd love to, but I don't know how to use one.

**Comment by marcussacana** [comment]
See the readme in the rar
