### ISSUE TITLE
Can't extract mwarehook due old version of it.

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/MwareStuff#21]
Hi Fisch here again.
I recently downloanded your mwarehook but his assets can't be loaded due to old version or something.What should I do?
Thanks for reply
![eror](https://user-images.githubusercontent.com/69847532/105172080-5a2dd900-5b1f-11eb-82d6-f99373a5d2ea.PNG)

**Comment by fisch123456** [comment]
Sorry have not install net extension.

**Comment by marcussacana** [comment]
Anyway what is old is your visual studio, not the source, You should use visual studio 2019 to build the tools
