### ISSUE TITLE
Game request

### ISSUE THREAD

**Issue by TennisChad** [marcussacana/MwareStuff#22]
Requesting https://vndb.org/r61822 
I drag the exe to the MwareKeyFinder injector and this happen:

```
Exceção Sem Tratamento: System.Exception: Failed to create the process
   em VNX.Tools.CreateProcessSuspended(String Filename, String Arguments, String CurrentDirectory)
   em VNX.RemoteControl..ctor(String Filename, Process& CreatedProcess, String Arguments, String WorkingDirectory)
   em SRLInjector.Program.Main(String[] args) na E:\Users\Marcus\Documents\Visual Studio 2019\Projects\MwareStuff\SRLInjector\Program.cs:linha 83
```
There is a tool to extract the .NPK on **Zenhax** and this is the key for Kishin Hishou Demonbane:
`BE2802AD5E91DD8E26EAD6B161FEDB8A17E2362F53336D1B17D80AE955C05AED`
But there is no tool to repack them so far.
Here is the .exe and the script:
[Demonbane.zip](https://github.com/marcussacana/MwareStuff/files/5900039/Demonbane.zip)
[script.zip](https://github.com/marcussacana/MwareStuff/files/5900040/script.zip)

Thanks you anyway.

**Comment by marcussacana** [comment]
If you already have the key I didn't do anything, just read the readme.

**Comment by TennisChad** [comment]
I tried the key with NPK3Tool before and it didn't worked, so i thought the key was incorret, but i was just giving the wrong directory file lol,
 Well thanks for helping this poor soul.
