### ISSUE TITLE
npk3tool.exe crashed every time

### ISSUE THREAD

**Issue by seragakisei** [marcussacana/MwareStuff#23]
Hi Marcus! I found the key by using your tool! Thank you! 
I want to extract the cg by the key but the NPK3tool.exe crashed upon start... I cannot even input anything... 
The right step is type -KY & the key & cg.npk? But I can't type anything before it crashed...
What should I do? 
I am sorry to bother you here. Thank you in advance.

**Comment by marcussacana** [comment]
show me how looks like your command line and any comment of the error if the program display one.
It's impossible to me fix without any information.

**Comment by seragakisei** [comment]
I just clicked the NPK3tool executable and it showed up, then I tried to type something with it unexpectedly quitting... I didn't see any error displayed but it just quitted without reason...
And when I dragged the npk file into the npk3tool.exe, and typed "-KY YourKeyHere C:\YourGameNpkFileHere.npk", there's no response at all... 
Or should I use the visual studio tool? But I have no knowledge of this...
Sorry to bother you again, thank you ><

**Comment by marcussacana** [comment]
Isn't to you type the command line after the dragdrop, you must use the CMD to do that. The drag drop only work with games already supported by the tool

**Comment by marcussacana** [comment]
Friend, I really recommend you found someone that understand a bit more of computer before try to translate a game, i'm sure this don't will be your last problem... but whatever, don't drag&drop, this is the CMD but is to you type it, open the tool directory in the cmd then execute the command like in the example.

**Comment by seragakisei** [comment]
Thank you for explaining! I just want the cg files. >< I'll try it!!!! 
Sorry to bother you so many times...
Many thanks!!!!!
