### ISSUE TITLE
The Song of Saya (Steam): 18+ patch problem

### ISSUE THREAD

**Issue by NOGREE** [marcussacana/MwareStuff#24]
Hello Marcus! Sorry to distract you.
I do not know if it is possible to solve this problem, but I decided to try to write to you.

Your NPK3Tool unpacks "The Song of Saya" Steam version well. But if you install the 18+ patch (from the official site of JAST USA), then the installer repackages the files again and, most likely, changes the key to them. As a result, NPK3Tool crashes when trying to open new npk files "The Song of Saya". SRLInjector also stopped working when trying to find a key from these files.

Do you think it is possible to find out the key and force the program to unpack these files?
If you need it, I can provide you with the files you need. New repackaged files from the steam version and I can send the exe file of the patch purchased on the official website.
Write if needed.

**Comment by marcussacana** [comment]
SRLInjector worked without problem, maybe you should don't used it right, anyway I added native support to the +18 version.

**Comment by NOGREE** [comment]
@marcussacana Thank you so much, Marcus! I checked everything. The files are unpacked and packed. The test was successful.
Your program just got better.

Thank you for responding to my message so quickly ^_^
