### ISSUE TITLE
Possible support for the windows 10 release of Demonbane?

### ISSUE THREAD

**Issue by FernandTheFresh** [marcussacana/MwareStuff#25]
I was thinking of making a project where I ported the JAST translation over to the windows 10 release. In order to do this I need to find a way to unpack and repack the script files.

**Comment by marcussacana** [comment]
I can't guarantee anything since there may have been major changes in the engine, send me a link to download the game to my email.

**Comment by marcussacana** [comment]
Support 'Added' more one case when the MwareHook worked and I lost my time
