### ISSUE TITLE
Possible support for Dramatical Murder (Jast version)

### ISSUE THREAD

**Issue by lazylabourer** [marcussacana/MwareStuff#26]
Hello, I hope it's okay to ask if it's possible to add support for Dramatical Murder, Jast's version, as it uses npk. SRLInjector throws out an error but works fine with Jast's version of YOU and ME and HER, so I doubt I'm using it incorrectly.
Thank you for your hard work!

**Comment by marcussacana** [comment]
send me link to download the game to my email

**Comment by lazylabourer** [comment]
Sent, thank you!

**Comment by marcussacana** [comment]
![https://i.imgur.com/X1jR9k5.png](https://i.imgur.com/X1jR9k5.png)

Working here.... well what ever
