### ISSUE TITLE
UnauthorizedAccessException

### ISSUE THREAD

**Issue by offline2007** [marcussacana/MwareStuff#27]
First of all, thanks for you hard work!

Sadly I have a problem with extracting the script.npk file from the game Yoe and Me and Her.
I extracted the key without a problem, but when I try to extract the npk with the NPKTool,
the program just throws me an UnauthorizedAccessException error. I tried running it with administrator rights,
changed the folder and even tried it on an other system, but nothing is changing.

Am I doing something wrong here? 
![Screenshot 2021-07-03 171338](https://user-images.githubusercontent.com/35119853/124358761-0a9d1e80-dc22-11eb-821c-c97ad6ff8b0a.png)

**Comment by marcussacana** [comment]
strange, a folder with the same name exists?
if you have visual studio you can try run while debugging to see the problem.

**Comment by marcussacana** [comment]
also send me the command line and the file to me test here

**Comment by offline2007** [comment]
Yeah, the folder exists 100%. I tried it just in the root directory of my second disk and in two other folders.
I don't have Visual Studio installed, but I can install it and try running it while debugging like you suggested, but my knowledge in Visual Studio is really limited.

Here the command line and file that I used:
NPK3Tool.exe -KY E7E8A5F99BAF7C73AE6BDF3D8C90262FF25025A12DB539F9CFD6E8E57975B798 E:\script.npk
[script.zip](https://github.com/marcussacana/MwareStuff/files/6759177/script.zip)

**Comment by marcussacana** [comment]
False positive, your file is marked as read-only in his proprieties, disable the read-only.

**Comment by offline2007** [comment]
Oh wow, I feeling kinda stupid right now, though I'm not sure why the file was set to read-only in the first place. Thanks though.... and sorry :<
