### ISSUE TITLE
Could support DRAMAtical Murder (Steam Version)

### ISSUE THREAD

**Issue by raskisenpai** [marcussacana/MwareStuff#29]
Hi marcus,I used your tools to get the files from npk in  DRAMAtical Murder (Steam Version), but it didn't support it natively.
Can add a native support with it?
I already use SRLInjector to get the Code.
![Snipaste_2021-08-25_17-51-30](https://user-images.githubusercontent.com/49297379/130772535-336c2541-e52b-497f-9bda-2689ba10a624.png)

**Comment by TUsolfy** [comment]
I sent you the file. Thank you!

**Comment by marcussacana** [comment]
Ok

**Comment by marcussacana** [comment]
added

**Comment by TUsolfy** [comment]
Thank you!
