### ISSUE TITLE
Question about font

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/MwareStuff#3]
Just a quick question, you know if there's a way to reduce the ingame size of the font on those games? Especially in tokyo necro.

Thanks!

**Comment by marcussacana** [comment]
At least in the Totono I managed to change the font size with the [SRL]
[You and Me and Her [Font Mod].zip](https://github.com/marcussacana/MwareStuff/files/4641343/You.and.Me.and.Her.Font.Mod.zip)

**Comment by Tfausx** [comment]
Yes, checked right now and totono + majikoi changes the size of the font perfectly! thank you so much! So, there's no chance for Tokyo Necro? The only different point in the font between those games it's maji + totono uses normal .ttf font, tokyo necro on other side, uses images for the font.

**Comment by marcussacana** [comment]
Yeah, don't will be too easy since the font is a image, will be required a font editor tool to this game.
I tried force the game load font from otf files, but looks like the .bin font usage is something written in the game executable and can't be easy changed.

**Comment by marcussacana** [comment]
but if you want just reduce the font size, what about you change the rename the font files?
For example, the min26a is the biggest font, the second one is the rodan17db, maybe you can try replace the rodan17db.bin and rodan17db0.png with the min26a

**Comment by Tfausx** [comment]
Works perfect! Thank you so much again for all the support! You're a really kindle person! Have a nice day!
