### ISSUE TITLE
Problems with video files

### ISSUE THREAD

**Issue by TUsolfy** [marcussacana/MwareStuff#30]
Hello.
There was a problem translating the game.
The dx.npk file is a video file.
Unpacking this file was successful.
But when I repack this file, the video doesn't play in the game.
Even if you repack the original unedited video file, it will not work properly in the game.
Is there any way to solve this problem?
I would like to add subtitles to this video.
I will send you the file.
The game is DRAMAtical Murder (Steam).

**Comment by marcussacana** [comment]
You will need copy the original video NPK settings, use this https://github.com/marcussacana/MwareStuff/blob/master/NPK3Tool/NPK%20File%20Table.bt

Then with the parameter -dumptable the npk info will be dumped and you can analyze in the 010Editor,
Usually the problem should be related with compression or the max section size

**Comment by TUsolfy** [comment]
Thank you for the reply.
As you said, I opened the file with 010editer.
I compared the original npk with the repacked npk,
The difference is the sort order of video files and
size of struct NPK3Entry Entry,
Value of uint SegmentCount,
The size of the struct NPKSegmentInfo SegmentsInfo.

When repacking the video folder, is it correct to enter the MS value in the options?
I tried several combinations but it didn't solve the problem (-MS 0x11B5C -cp 1, -MS 0x13363 -cp 0 ...)

![00](https://user-images.githubusercontent.com/66259008/135436295-d2d8da57-5da0-460a-b7b4-6e0ed27d9465.jpg)

**Comment by marcussacana** [comment]
the original should have a 'max sector size', just look in the first entry of the sections and his 'AlignedSize' is our max section size that you can use the -MS parameter... Well, i'm not sure if is AlignedSize or RealSize, have a good time that I don't worked with this engine.

**Comment by TUsolfy** [comment]
I entered the value of uint AlignedSize or the sum of the sizes of all uint AlignedSizes, but the video file did not play.
What mistakes have I made?
![01](https://user-images.githubusercontent.com/66259008/135609595-4d5ec6d9-ab10-4d93-ae1c-c23761f8530e.jpg)

**Comment by marcussacana** [comment]
Nahh, my mistake, as I said, a good time without deal with this engine, try use the DecompressedSize value

**Comment by marcussacana** [comment]
by the way, you did wrong, isn't the 'size' that you must to copy, you need to look that 'value' column

**Comment by marcussacana** [comment]
sould be one of those values.
![image](https://user-images.githubusercontent.com/10576957/135612399-19acc9ba-3934-48d2-b064-bfe321183d06.png)

**Comment by TUsolfy** [comment]
Thank you!
The video file plays without any problems.
I would not have been able to solve it by myself.
