### ISSUE TITLE
Could you support for Togainu no Chi(Steam)?

### ISSUE THREAD

**Issue by TUsolfy** [marcussacana/MwareStuff#31]
Hello.
Could you add support for Togainu no Chi(Steam version)?
Unpacking this file was successful, but the game does not run when the repacked file is used.
I will send you the game executable and script file.

This is key and npk information.
1884B591CE89E6ADF09D769E33E2A8895C02AB5C3AFC8F7E70D86FB09236DC33
NPK2
Encryption Key Found:
0x18, 0x84, 0xB5, 0x91, 0xCE, 0x89, 0xE6, 0xAD, 0xF0, 0x9D, 0x76, 0x9E, 0x33, 0xE2, 0xA8, 0x89, 0x5C, 0x02, 0xAB, 0x5C, 0x3A, 0xFC, 0x8F, 0x7E, 0x70, 0xD8, 0x6F, 0xB0, 0x92, 0x36, 0xDC, 0x33

**Comment by marcussacana** [comment]
Read this first, #30

**Comment by TUsolfy** [comment]
Thank you!
I have succeeded in running the game.
I solved the problem thanks to you.
