### ISSUE TITLE
Both tools crashing immediately

### ISSUE THREAD

**Issue by Shierke** [marcussacana/MwareStuff#32]
Hey there, thanks for your great work for extraction tool

Not sure why but I'm facing an issue where when I drag and drop onto NPK3Tool then it just immediately closes with no output, same for MwareKeyFinder; I drag and drop and it will just close immediately when I drop the file. Even one single key input on either command line causes the applications to close immediately. Any idea? Thanks

https://user-images.githubusercontent.com/95281720/144027253-51e05226-df0c-421b-a175-43bf15384e06.mp4

Unfortunately drag and drop or pressing a key instantly closes both tools. Am I missing some dependency? I've gone to reinstall all runtime variables and nothing has changed

**Comment by marcussacana** [comment]
Drag and Drop the .npk file to the NPK3Tool exe

**Comment by Shierke** [comment]
ah thanks, my bad for misunderstanding drag and drop. appreciated!
