### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by shzkr** [marcussacana/MwareStuff#33]
Hello here. I downloaded this and how to use it? with CMD? how to extract / unpack .npk files? what command should I use? Can you help me please. there is no any "help" or "tips" here. Also I tried this: https://github.com/rsa9000/npk-tools, and this: https://github.com/crskycode/MwareStuff/releases but nothing is working.

**Comment by marcussacana** [comment]
Inside the MwareKeyFinder.rar have a "How To.txt", take a look
