### ISSUE TITLE
Totono error (insert video) 

### ISSUE THREAD

**Issue by tsulocalize** [marcussacana/MwareStuff#34]
Hello, I'm an user try to localize Totono(steam).

Totono's videos are in dx.npk.

Even I unpack and repack with the orginal video files, but it doesn't play in the game.

However, my original file (specifically mv_logo1_black.wmv) is played well!

I confused what the problem is.

Thank you for your hard work.

**Comment by marcussacana** [comment]
Read this issue https://github.com/marcussacana/MwareStuff/issues/30

**Comment by tsulocalize** [comment]
> Read this issue #30

Thank you for the reply.

With 010 Editor, I used NPK File Table.bt.

But when I run(F5) it, an error occurs [*ERROR Line 48: Invalid array size in declaration. ]

It must be the last question.

**Comment by marcussacana** [comment]
Probabbly you executed the template in the .npk you must use in the file table dump that you can get as said.
Also this isn't a script, you must run as template and not a script

**Comment by tsulocalize** [comment]
Thank you very much! It works well!
I appreciate it.
