### ISSUE TITLE
Can't unpack "Full Metal Daemon Muramasa"

### ISSUE THREAD

**Issue by NOGREE** [marcussacana/MwareStuff#35]
Greetings! Maybe I'm doing something wrong, but MwareKeyFinder couldn't find the key to "Full Metal Daemon Muramasa" (or Soukou Akki Muramasa). Which was recently reissued by JAST USA.

Is it possible to add support for opening files from this game?

I attach the lightest files to the message. Like font.npk, particle.npk
[FMDM.zip](https://github.com/marcussacana/MwareStuff/files/7787098/FMDM.zip)

**Comment by marcussacana** [comment]
I will need the entire game to check, send to my email: ddtank.marcus@gmail.com

**Comment by NOGREE** [comment]
Good! I wrote to you in the mail.

**Comment by marcussacana** [comment]
The tool worked here
![image](https://user-images.githubusercontent.com/10576957/147626309-ffd53522-3e26-4b57-9d96-21b2d97681ca.png)

Anyway, I added native support to the tool.
