### ISSUE TITLE
Dramatical Murders (Steam) isn't working with the SRLInjector.exe

### ISSUE THREAD

**Issue by Ikusth** [marcussacana/MwareStuff#36]
I drag the game's .exe to SLRInjector.exe and nothing happens, the .exe just closes, maybe the Jast USA uncensored patch is causing conflict?

NPK3Tool.exe opens but closes in less than a second.

**Comment by marcussacana** [comment]
You removed the steam stub? The Steam DRM can prevent the tool to work.

**Comment by marcussacana** [comment]
try this: https://github.com/atom0s/Steamless/releases

**Comment by Ikusth** [comment]
It worked, thanks.
