### ISSUE TITLE
Soukou Akki Muramasa Janen Hen 

### ISSUE THREAD

**Issue by jenduis** [marcussacana/MwareStuff#37]
Muramasa's free spin off only in jp does not work with the MwareKeyFinder instead just boots up the game without giving any prompt. Jast's Muramasa works with the finder though. My computer is in japanese locale

https://user-images.githubusercontent.com/66085054/165144744-3b0aa133-db65-476e-aa76-5a636c992f15.mp4

.

**Comment by marcussacana** [comment]
This game don't use the Mware engine then isn't supported.

**Comment by jenduis** [comment]
Ugh just realized that I typed the name of the wrong spin off the one I'm trying is actually this https://vndb.org/v19151 if it changes anything

**Comment by marcussacana** [comment]
.npa files are of the legacy nitro plus engine, .npk files are for Mware Engine, the game in that video isn't using Mware engine at all.
