### ISSUE TITLE
Text goes out of the text box

### ISSUE THREAD

**Issue by Lumminal** [marcussacana/MwareStuff#38]
I got the tools working correctly, the font
already supports my language so I didn't
change it but one problem that I have 
encountered in game is that the text
goes out of the text box and I wonder
if there's any way to add a line break
or something to fix this. The game is full metal Daemon Muramasa. Thanks

**Comment by marcussacana** [comment]
This will required change the font size.
You need know if the game use a otf or windows font, if yes, use the StringReloads tool to resize the font.
If the game use a font in the MwareEngine format, this is the max that I can hint you:
https://github.com/marcussacana/MwareStuff/issues/3#issuecomment-629881483

**Comment by marcussacana** [comment]
That's strange, enable the SRL log and set the loglevel to TRACE and see if any error information is shown.

**Comment by Lumminal** [comment]
https://pastebin.com/FEfj0d8b

The log crashes there

Thanks again

**Comment by marcussacana** [comment]
Not sure if is related, but you put a invalid font name.
The SRL don't expect a font file name, but a font face name.
if you want load your own font file, enable the LoadLocalFonts
and set the Facename to your font facename.

**Comment by Lumminal** [comment]
Alright! It works! I just had to change the to parameter to Droid Serif instead of droidserif-muramasa.ttf like you said. Thanks a lot marcus, and generally thanks for helping other people quick and providing useful tools for us to use! I'll be sure to donate something soon when I get the chance.
