### ISSUE TITLE
Problem repacking CG.NPK - Full Metal Daemon Muramasa/JAST

### ISSUE THREAD

**Issue by Akatsukidarkx** [marcussacana/MwareStuff#39]
Hello, the problem occurs when repacking the CG.NPK file.

In this case the game loads fine at the beginning (as the edited "WARNING" image is displayed), but after the initial "Nitro+" image the game closes automatically. Just in case, I generated an npk with the original files and the problem still occurs.
[https://mega.nz/file/uNQ1DSgS#hFgc2A10oiJhdKbq1dIfzCZCIBw_y80Am2_3odX4ZGI](url)

This problem has not happened with the script.npk file so far.

**Comment by marcussacana** [comment]
Read this issue https://github.com/marcussacana/MwareStuff/issues/30

**Comment by Akatsukidarkx** [comment]
On the right image is the original, on the left the modified file (without putting anything in -MS).

I tried with the -MS values 0xC0400, D640, D63C, D632 and it still doesn't work. 

Maybe it is because of the SegmentationMode value, how could this value be changed?

I don't know if it was the right option, but I was trying with "-SG 0" but I didn't see that value changing.
![Captura_de_pantalla_2022-09-08_221642](https://user-images.githubusercontent.com/45851149/189267550-379e8477-553b-4b1f-8696-3de146b665fb.png)

**Comment by marcussacana** [comment]
check the value in a big file, I'm suposing here after  the first warning image, a intro video is played, is that right? then, check the value of that video

**Comment by Akatsukidarkx** [comment]
Thank you very much, I found the solution, in the end it was because of the Segmentation (I was typing wrong in command) and because of the format of the images.

Apparently, unlike Totono that loaded images in *png without problem, in Muramasa they must be in *.WebP format.
