### ISSUE TITLE
You and me and her steam release compatibility

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/MwareStuff#4]
Hi again Marcus, i hope you're having a nice day, today i bough Totono in his Steam release with the intention of working in that version for translation but with the actual tools, not work. It's there a posibility to fix that? 

Thanks in advance and sorry for the inconvienence!

**Comment by marcussacana** [comment]
The MwareHook don't worked with the release?
Anyway, I will need the game downloaded to do that, upload it and send to my email a link

**Comment by Tfausx** [comment]
Nope, not work. And sure, sent it right now! 

Thanks for your time

**Comment by marcussacana** [comment]
Downloading, well, probbly the MwareHook don't worked because you don't cracked the Steam Stub, but I will confirm here, if is the case I will update the MwareHook to detect the steam stub and ask for crack it.

**Comment by marcussacana** [comment]
My friend, you didn't said the MwareHook don't worked?
![image](https://user-images.githubusercontent.com/10576957/83204070-49100200-a121-11ea-919f-86206ab70bb4.png)
Well, whatever, I will update the NPKTool... just a sec.

**Comment by marcussacana** [comment]
Test it, if everything works close the issue.

**Comment by Tfausx** [comment]
All works perfect! Thanks again for your time!

Have a nice day!
