### ISSUE TITLE
Slow Damage DL

### ISSUE THREAD

**Issue by shinneon** [marcussacana/MwareStuff#47]
Hello! I test the Slowdamage downloaded from DLsite and its not working. I'm wondering if it is able to add DL version?
I can provide the files if you need them.

**Comment by shinneon** [comment]
![IMG_1290](https://github.com/marcussacana/MwareStuff/assets/145994704/c65152be-3fe8-4a14-83f1-bec11e97ddf7)
![IMG_1291](https://github.com/marcussacana/MwareStuff/assets/145994704/b155a573-ca59-4a3e-8ea4-09bc43b54691)
Here's the result of the test.

**Comment by marcussacana** [comment]
This game from DLSite it might be using some type of DRM, can you find an cracked version and try it again?

**Comment by shinneon** [comment]
I find a cracked version and tried it, but it seems to be the same result.

**Comment by marcussacana** [comment]
Upload the game + crack in google drive and send the link to my email: ddtank.marcus[at]gmail.com

**Comment by shinneon** [comment]
I've sent an email. Please check.

**Comment by marcussacana** [comment]
The game that you sent does not have the crack.

**Comment by shinneon** [comment]
I've sent another one. I only have these two files.

**Comment by marcussacana** [comment]
![image](https://github.com/marcussacana/MwareStuff/assets/10576957/35da4a0d-2a3f-49d8-8dca-5672bcc89d15)
