### ISSUE TITLE
Can't extract with the NPK3Tool

### ISSUE THREAD

**Issue by Joltyboy** [marcussacana/MwareStuff#48]
First of all, this is the first time I'm trying to mess with a game's files and translate it myself, so I'm totally clueless about everything, and I would appreciate if you could give me some advisement for where to start and stuff. (Also I'm Brazillian too, if you can continue the discussion in portuguese I would appreciate). 

Well, I downloaded the tools NPK3Tool and MwareKeyFinder, I'm trying to translate "You and Me and Her" from Steam. I had no problem with finding the game key, now I'm trying to extract the script.npk dragging and dropping it onto the NPK3Tool.exe but no response, when I drop it my taskbar shows that something opened, but it instantly closes and no CMD appears. Also this is a backup file for the game, but I tested both backup and steam files and none of them worked.

Again, sorry for being a dummy, this is a new thing for me and I'm excited to try it out.

**Comment by marcussacana** [comment]
It's better talk in english for future reference of anyone reading this.

Probabbly your problem is that you are missing with the .NET Core 3.1 Runtime, you need download from microsoft site and install it before start using the NPK3Tool, the MwareKeyFinder works because it uses .Net Framework 4.6 and is natively shipped with newer versions of the windows.

**Comment by Joltyboy** [comment]
Now it worked, thanks man.

By the way, as I said before this is my first time messing with hex code, there's any basic guide avaliable around that you know? I'm not in a hurry to learn so I would appreciate it.
Maybe an alternative way to contact you, if it's not going to bother of course XD, but if you don't want to then thanks anyway

**Comment by marcussacana** [comment]
Hex are just numbers there's no much for learn about, but you are probabbly looking for data structure, google for that.
