### ISSUE TITLE
I have no idea how to use SacanaWrapper and PluginManager

### ISSUE THREAD

**Issue by Joltyboy** [marcussacana/MwareStuff#49]
So, as I said in my previous post, I was trying to mess with the Hex Code of the script from ToToNo (Steam), but I had some issues when showing the letters in the textbox ingame, so I was wandering around here to find a solution and found out about your plugin NUTEditor, and I don't know how to use it or download it, so I tried to download the PluginManager and see how it goes
![image](https://github.com/marcussacana/MwareStuff/assets/146897428/0a393bda-ddac-4b7a-b400-c057c6ddb6b5)
When I run it, it appears an error message (sorry for the different language if anyone else's reading it xd)
![image](https://github.com/marcussacana/MwareStuff/assets/146897428/3a455c51-ba20-43a2-b059-4d39501e779d)
If you need the details attached, just reply
And when I click continue, this appears
![image](https://github.com/marcussacana/MwareStuff/assets/146897428/9fd3c95b-faea-48e9-8d89-686b4915377c)
By the way, the Plugins file is empty, should it be supposed to have anything inside?
As I read another Issue question about a similar problem, I understood I needed to Drag and Drop the .nut file on the StringTool.exe to be able to edit it, but when I do it, it happens the same as my last problem with NPK3Tool, it won't open, it appears that something opened in the taskbar but it closes instantly
If I'm correct about this NUTEditor plugin, it should be a complement for another application, the problem is, I have no idea what to do with it

Again, sorry if I'm bothering and for my ignorance, it's all new for me, I just wanna translate the game's script and that's all.
Thank you for your patience.

**Comment by Joltyboy** [comment]
By the way, another question I have about the script modification
I'm using just the raw "HxD" hex editor to do it, when I tried to translate the first line of the game, it needed an "é", but it somehow appears as a blank rectangle
![image](https://github.com/marcussacana/MwareStuff/assets/146897428/3d60bc87-bcd0-4d8e-b77c-8ee027ee7caf)
I still don't know how the data structure works entirely, but by my tests I can't add more null bytes than the original amount, if I do it the entire text becomes rectangles or simply crashes
But as I searched in this forum, I see you actually translated that piece of the game too, and for you the accentuation works
Here's your own print of that
![image](https://github.com/marcussacana/MwareStuff/assets/146897428/adf50cbf-fc37-491e-b6b3-f32b5b3eb4d6)
My question is, did you messed with the font of the game for that? or was it work of the NUTEditor?

Again, I'm a newbie, be patient with me please

**Comment by marcussacana** [comment]
I can't say what is wrong without the details content that you left out.
Also, just to be sure StringTool and PMan.exe should be extracted both in the same directory to works.

**Comment by Joltyboy** [comment]
here is
Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.IO.FileNotFoundException: C:\Users\Erik\Documents\Translate tools\Plugin.Manager\SacanaWrapper.dll
   em System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   em PMan.Updater.TreeRepositorie() na C:\projects\sacanawrapper\PMan\Update.cs:linha 20
   em PMan.Main.Form1_Load(Object sender, EventArgs e) na C:\projects\sacanawrapper\PMan\Main.cs:linha 26
   em System.Windows.Forms.Form.OnLoad(EventArgs e)
   em System.Windows.Forms.Form.OnCreateControl()
   em System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   em System.Windows.Forms.Control.CreateControl()
   em System.Windows.Forms.Control.WmShowWindow(Message& m)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.Form.WmShowWindow(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assemblies Carregados **************
mscorlib
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PMan
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 1.0.0.0
    Base de Código: file:///C:/Users/Erik/Documents/Translate%20tools/Plugin.Manager/PMan.exe
----------------------------------------
System
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9172.0 built by: NET481REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9037.0 built by: NET481REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9037.0 built by: NET481REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9037.0 built by: NET481REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9037.0 built by: NET481REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.9037.0 built by: NET481REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Depuração JIT **************
Para habilitar a depuração just-in-time (JIT), o arquivo .config deste
aplicativo ou computador (machine.config) deve ter o valor
jitDebugging definido na seção system.windows.forms.
O aplicativo também deve ser compilado com a depuração
habilitada.

Por exemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando a depuração JIT está habilitada, qualquer exceção sem tratamento
será enviada ao depurador JIT registrado no computador,
em vez de ser tratada nesta caixa de diálogo.

**by the way, when you say stringtool and pman extracted both in the same directory you mean in the same folder, right?**

**Comment by marcussacana** [comment]
![image](https://github.com/marcussacana/MwareStuff/assets/10576957/3ddfe878-b9da-4950-a851-8add60345eea)
Your problem is probabbly because you didn't extracted correctly, then yes, both files should be in the same folder.

**Comment by Joltyboy** [comment]
Yeah it was my mistake, it's solved now

Now, I would like to go back to my second question, I see you translated yourself the start of the game as well, and you managed to place the accents, how did you do that? did you messed with the fonts? letters like "é", "ã" or "ô" don't show correctly for me ingame.
If you indeed messed with the fonts, can you give me advisement of how to do it? (I already decoded the font folder btw)

**Comment by marcussacana** [comment]
Only changing the font, it's impossible to put accents in the script without patch the engine.
