### ISSUE TITLE
Cyrillic text is not displayed (You and Me and Her)

### ISSUE THREAD

**Issue by MishaIac** [marcussacana/MwareStuff#5]
Hey. I had a problem with the сyrillic text in the game You and Me and Her (Jast Usa release, no Steam) I unpacked the script.npk file, and edited the first script file via NUTEditor, and packed everything back. The game starts normally, but the game itself does not see the text, as if there are empty lines. I would be grateful for any help.

I also enclose a sample script.npk with Russian text inside: [script.npk rus.zip](https://github.com/marcussacana/MwareStuff/files/4707570/script.npk.rus.zip)

![image](https://user-images.githubusercontent.com/47920105/83351201-9ae7a080-a34a-11ea-9f53-e43828366d76.png)

**Comment by marcussacana** [comment]
Probabbly the font is missing the characters or you installed the wrong version o the NUTEditor
The ToToNo NUT files uses the UTF8 encoding.
The fonts are inside the fonts.npk.

**Comment by MishaIac** [comment]
> Probabbly the font is missing the characters or you installed the wrong version o the NUTEditor
> The ToToNo NUT files uses the UTF8 encoding.
> The fonts are inside the fonts.npk.

No, the fonts support the Cyrillic alphabet, and I installed the correct version of NUTEditor, because with it I was able to change the English text.

The engine itself supports the Cyrillic alphabet. I could find out by decompiling the .nut file, and leaving it like that without compiling it back. Of course, you can decompile all .nut files, and the game will work fine, but not everything is so smooth.

In order to decompile scripts, you first need to remove these first values through the hex editorNo, the fonts support the Cyrillic alphabet, and I installed the correct version of NUTEditor, because with it I was able to change the English text.

The engine itself supports the Cyrillic alphabet. I could find out by decompiling the .nut file, and leaving it like that without compiling it back. Of course, you can decompile all .nut files, and the game will work fine, but not everything is so smooth.

In order to decompile scripts, you first need to remove these first values through the hex editor:
![image](https://user-images.githubusercontent.com/47920105/83356400-992fd400-a36e-11ea-80ec-cd939e60cfde.png)

And then use [NutCracker](https://github.com/marcussacana/MwareStuff/files/4707909/NutCracker.zip) to decompile them.

There are no problems with a0001.nut, but there are problems with the rest. The fact is that the rest .nut has Japanese characters, and it looks like NutCracker does not support anything except ANSI, and when decompiling, this happens:
![image](https://user-images.githubusercontent.com/47920105/83356601-d21c7880-a36f-11ea-846c-36bdba8ac9b9.png)
NUTEditor: 
![image](https://user-images.githubusercontent.com/47920105/83356638-19a30480-a370-11ea-9b3b-bb67ed7b909d.png)

Most likely, the Cyrillic alphabet does not work in compiled form, so the only way to make the game work with the Cyrillic alphabet is to use decompiled scripts, but unfortunately, I do not have a normal decompiler :(

**Comment by MishaIac** [comment]
Here, here I used the decompiled a0001.nut script
![image](https://user-images.githubusercontent.com/47920105/83357056-b36bb100-a372-11ea-81df-60d2620ce2c1.png)

**Comment by marcussacana** [comment]
This is strange... send to me the working russian script and the one that isn't working, i will take a look.

**Comment by MishaIac** [comment]
Lol, it turned out that it was my mistake. The compiled text works perfectly. Sorry to open this question. Thanks for this utility. :)
