### ISSUE TITLE
How do I patch the engine?

### ISSUE THREAD

**Issue by Joltyboy** [marcussacana/MwareStuff#50]
In the last issue I had with the tools, I asked about the accents not working ingame and got replied with:

> Only changing the font, it's impossible to put accents in the script without patch the engine.

And I was wondering about it and decided to check it out myself, so I opened the decoded .ttf files of the ToToNo (Steam) game font to see if it has the letters with accent I was looking for, I used the FontForge in order to find it
![image](https://github.com/marcussacana/MwareStuff/assets/146897428/217f21fd-2fe9-4bef-99b2-35f9791da5f8)
![image](https://github.com/marcussacana/MwareStuff/assets/146897428/61c896fa-4b82-485e-bed8-7f0d22371bc5)

As you can see, the files have the letters I was looking for, but somehow it don't shows ingame
I was told that's only possible if patching the game engine, so my question is, **how do I do it?**
I mean, am I doing something wrong? Losing something?
I roamed around the forum and found no clue about a semelhant issue, so I wanted to ask about it

I appreciate if you can help me with it

**Comment by marcussacana** [comment]
The japanese softwares are made for display japanese texts, essentially many visual novels aren't able to store in their files the text, basically "impossible" without patch the engine, but this patch is basically modify the engine to use unicode encoding instead SJIS, and this is an very advanced task and you can just forget that, in the case of mware, some builds of the engine it uses unicode by default it may make the things a bit more realist but still hard.
So, patch the engine is an option only when you have an hacker with experience for do it.
The characters in the font don't means is an supported character by the game, what you need to do is pick an japanese character in the font and change his apparence to look like an accent character, and in the game script you put that japanese character and the game will display an accent instead.
