### ISSUE TITLE
application with startup parameters

### ISSUE THREAD

**Issue by Mrqqeat** [marcussacana/MwareStuff#51]
If the application comes with startup parameters, how do I drag and drop it to SRLInjector.exe

**Comment by marcussacana** [comment]
Good question, there are no support for this case but you can edit the code here to add command line args
https://github.com/marcussacana/MwareStuff/blob/master/SRLInjector/Program.cs#L83

**Comment by Mrqqeat** [comment]
> Good question, there are no support for this case but you can edit the code here to add command line args https://github.com/marcussacana/MwareStuff/blob/master/SRLInjector/Program.cs#L83

okay, I understand, thank you
