### ISSUE TITLE
The program shuts down when I do anything

### ISSUE THREAD

**Issue by MrGoraj** [marcussacana/MwareStuff#53]
As in the video, the program shuts down after typing one character or doing anything else.

https://github.com/marcussacana/MwareStuff/assets/32809530/ff236ed6-923c-48f0-a0de-e5b8e8b317c3

**Comment by marcussacana** [comment]
Read it.

**Comment by MrGoraj** [comment]
> Read it.

Read what? 

If you're referring to the instructions in the console, then what I'm trying to say is that when I try to type any command in the console, that console shuts down before I can complete it.

I type "-" and the console shuts down before I can enter the second character. 

I haven't pressed any other key to close the console.

**Comment by marcussacana** [comment]
This is a CLI tool not an window app.
![image](https://github.com/marcussacana/MwareStuff/assets/10576957/271f4b47-ae35-4296-9d9d-fa8420ea2652)
If you don't know how to use CLI you can just drag&drop your npk to the NPKTool.exe.

**Comment by MrGoraj** [comment]
> This is a CLI tool not an window app. ![image](https://private-user-images.githubusercontent.com/10576957/293516767-271f4b47-ae35-4296-9d9d-fa8420ea2652.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDM3NTUsIm5iZiI6MTcwNDA0MzQ1NSwicGF0aCI6Ii8xMDU3Njk1Ny8yOTM1MTY3NjctMjcxZjRiNDctYWUzNS00Mjk2LTlkOWQtZmE4NDIwZWEyNjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE3MjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYjc2ZDEwMGU3ZTJjM2VhZDVkMzVjMjk3MmE3MDI3NDcyMWE4MmQyZjg2MTcyNWRlNGE2YTYxMzk0NDUwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uyMx6Xg9vTI4oDrCZZQH6jwQCJOqTsjMxlaECRTzmQk) If you don't know how to use CLI you can just drag&drop your npk to the NPKTool.exe.

I know, I've used several tools that work similarly.

What I am reporting is that the program is spontaneously shutting down BEFORE I HAVE TYPED ANYTHING.

**Comment by marcussacana** [comment]
Because you shouldn't type anything in that window, isn't made for that,
CLI tools are tools to be integrated in automation process, this mean that the tool will do what the command that you gave asked, that window appear when you try to open the tool without any command for what to do.
The correct usage of the tool is the command line prompt, if you don't know how to use you can drag and drop the NPK in the NPKTool.exe file and it will open a more intuitive way to use it.
