### ISSUE TITLE
Can't open NPK3Tool and can't drag&drop the executable

### ISSUE THREAD

**Issue by Kinariha1110** [marcussacana/MwareStuff#56]
Hi! I want to create a French translation patch for Totono, but whenever I try to drag&drop the executable in the SRLInjector, it closes right after, and I can't even open NPK3Tool. What should I do?

**Comment by marcussacana** [comment]
not sure too, the tool may be failing to acess the file, try use the command line manually instead.

**Comment by Kinariha1110** [comment]
I managed to solve the problem : i just had to install .net runtime. Thank you for your help
