### ISSUE TITLE
Games crashes after replacing original .npk with repacked .npk (Totono)

### ISSUE THREAD

**Issue by Kinariha1110** [marcussacana/MwareStuff#57]
Hello! I know this issues has already been reported here (#1) but to be honest it didn't help me at all. I tried several times to repack the script.npk file, but nothing changes ; the game crashes when the "Life is like a staircase." text is about to appear. Any idea on what I should do you solve the problem?

**Comment by marcussacana** [comment]
Try #30

**Comment by Khrisideus** [comment]
Got the same error. I tried following #30 but with the script.npk file, but it crashed anyways. From what I understood, you need to repack using the -MS parameter with the value from one of those field. Is that right ?
![image](https://github.com/marcussacana/MwareStuff/assets/99700394/bc207008-7276-4191-b098-4f825720578f)
'cause that's what I did (I removed the h at the end btw) but after changing the script.npk file, it still crashes no matter which of those value I use

**Comment by marcussacana** [comment]
test enable/disable those options (one per time)
```
-MV [1/2]         Set the NPK repack minor version
-SG [1/0]          Enable/Disable NPK Segmentation (Auto)
-FG [1/0]          Enable/Disable NPK Segmentation (Forced)
-CP [1/0]          Enable/Disable NPK Compression
 ```
totono is a game that I used to create this tool so it should be working.

**Comment by Khrisideus** [comment]
Thanks for the quick answer! I tried all of that, without the -ms parameter, with the -ms with alignedsize and -ms with decompressedsize, but no matter what, the game keeps crashing

**Comment by marcussacana** [comment]
send me the original script.npk, the modified script.npk and the encryption key if you used a unsupported game, I'm not in home now but I will try check what might be wrong later.

**Comment by Khrisideus** [comment]
Here are both the scripts files. The game is supported, it's "You and Me and Her (Steam)". Thanks a lot for your time
[Scripts.zip](https://github.com/marcussacana/MwareStuff/files/15328035/Scripts.zip)
Thanks a lot for your time

**Comment by marcussacana** [comment]
check if the game crash with this one
[script.zip](https://github.com/marcussacana/MwareStuff/files/15342757/script.zip)

**Comment by Khrisideus** [comment]
Yes it works! How did you do?

**Comment by Khrisideus** [comment]
It works when I don't modify any file, but if I try to change the text in any file in the "script.npk~\media\script\lang\en" folder (like for exemple a0001.nut) which seems to be the files containing the script, the game crashes when file's content is about to show. Are those not the files I should modify ?

**Comment by marcussacana** [comment]
try extract again, if the repacked files can be extracted then it may be a problem of the nut editor tool

**Comment by Khrisideus** [comment]
Is the nut editor supposed to work on its own? Because there's only a class that isn't used by any project. Or am I supposed to create a .net project that will use the NutEditor DLL to edit the files?

**Comment by marcussacana** [comment]
https://github.com/marcussacana/SacanaWrapper
