### ISSUE TITLE
Request to add support for 2 more games

### ISSUE THREAD

**Issue by Yukimi-end** [marcussacana/MwareStuff#6]
Hi, Marcus. I hope you are doing well. Well the thing is, I wanted to request you to add support for Sonicomi and the Song of Saya. I don't know if this would be any helpful but I tried dragging their respective executables over the SRLInjector tool, and in the case of Sonicomi it didn't do anything and just ran the game normally, here's the log file just in case:
![image](https://user-images.githubusercontent.com/30357779/83962855-a7965800-a866-11ea-9a88-71ac8dc59585.png)
In the case of the Song of Saya, it gave me this key:
![image](https://user-images.githubusercontent.com/30357779/83962884-f6dc8880-a866-11ea-9586-3e03e7dec79b.png)
Again, I don't know if you will find this any helpful at all, so if you need me to send you or do anything, you just say the word. By the way, I currently own the JAST version of Sonicomi and the Steam version of The Song of Saya.

Many thanks in advance

**Comment by marcussacana** [comment]
Upload a small original .mpk of this game,
Also press Ctrl + C in that dialog of the screenshot and paste the in this issue.

**Comment by marcussacana** [comment]
Also, send me a download link of this Sonicomi to my email.

**Comment by Yukimi-end** [comment]
Here's the key of the Song of Saya:
```
---------------------------
MwareKeyFinder - By Marcussacana
---------------------------
Encryption Key Found:
0x76, 0x3A, 0x14, 0x33, 0x8B, 0x0D, 0xAC, 0x04, 0x0A, 0xCC, 0xFC, 0x13, 0x85, 0x1C, 0xFA, 0xCB, 0xB2, 0x0B, 0x00, 0x0B, 0x01, 0xF8, 0x68, 0x48, 0x6B, 0x46, 0x0F, 0x8C, 0x34, 0xD4, 0x2A, 0x96
---------------------------
Aceptar   
---------------------------
```

And here's the script.npk file of said game:
[script.zip](https://github.com/marcussacana/MwareStuff/files/4742693/script.zip)

I'll make sure to send the download link as soon as I can.

**Comment by marcussacana** [comment]
Send me the song of saya too, I will need to test same things.

**Comment by marcussacana** [comment]
also, You already can extract with
`NPK3Tool.exe -KY 763A14338B0DAC040ACCFC13851CFACBB20B000B01F868486B460F8C34D42A96 -VS 2 -MV 2 C:\YourGameFileHere.npk`

**Comment by marcussacana** [comment]
Test the newest version and if works, close the issue.

**Comment by Yukimi-end** [comment]
Thank you very much, it worked for both of them.
By the way, do you know if there is any way to edit the fonts of Sonicomi, ever since the font.npk is filled with nothing but .bin and .png files?

**Comment by marcussacana** [comment]
Nop I know nothing about the font format of this engine.
