### ISSUE TITLE
How to extract Totono files

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/MwareStuff#8]
Hi I am new here and  I don't know how to use things, but I would like to ask you, how can I extract Totono files?I don't know how to do it without the exe, can you please help me?Thanks.

**Comment by marcussacana** [comment]
Drag&Drop

**Comment by fisch123456** [comment]
But where?
In which file?

**Comment by fisch123456** [comment]
I can see black that drag and drop window in visual studio but only when I want to start SRLInjector also when I drop the file nothing happens.

**Comment by fisch123456** [comment]
Ok I find it in the visual studio but I can't extract it.
Do you know where is the problem?

**Comment by fisch123456** [comment]
I found exe file in notecoreapprelease but it didn't opened and also when I tried to have file in the same directory it doesn't work either.What can I do?Sorry for incovenience.

**Comment by fisch123456** [comment]
Ok i come up on this Thanks for help
